In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("Salary_dataset.csv")

In [4]:
df.sample(5)

    Unnamed: 0  YearsExperience    Salary
6            6              3.1   60151.0
17          17              5.4   83089.0
28          28             10.4  122392.0
25          25              9.1  105583.0
10          10              4.0   63219.0

In [6]:
df.drop(columns=["Unnamed: 0"],inplace = True)

In [7]:
df.shape

(30, 2)

In [8]:
df.sample(5)

    YearsExperience    Salary
28             10.4  122392.0
15              5.0   67939.0
23              8.3  113813.0
26              9.6  116970.0
29             10.6  121873.0

In [43]:
# Linear Regression OLS implementation
class LinearRegressionOLS:
    def __init__(self):
        self.m = None
        self.b = None

    def fit(self, X_train, y_train):

        X_train = np.asarray(X_train).ravel()
        y_train = np.asarray(y_train).ravel()

        self.m = np.sum((X_train - X_train.mean()) *
                        (y_train - y_train.mean())) / \
                 np.sum((X_train - X_train.mean()) ** 2)

        self.b = y_train.mean() - self.m * X_train.mean()

        print("Coef:", self.m)
        print("Intercept:", self.b)

    def predict(self, X_test):
        X_test = np.asarray(X_test).ravel()
        return self.m * X_test + self.b

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns = ['Salary']),df['Salary'],test_size = 0.2,random_state = 42)

In [33]:
X_train.shape,X_test.shape

((24, 1), (6, 1))

In [44]:
# creating object
lr = LinearRegressionOLS()

In [45]:
lr.fit(X_train.values,y_train.values)

Coef: 9423.815323030978
Intercept: 24380.201479473697

In [21]:
from sklearn.linear_model import LinearRegression

In [22]:
lr = LinearRegression()

In [23]:
lr.fit(X_train,y_train)

LinearRegression()

In [25]:
lr.coef_

array([9423.81532303])

In [29]:
lr.intercept_

np.float64(24380.201479473704)